# Generated by Django 5.1.6 on 2025-05-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0016_remove_product_size_orderitem_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="size",
        ),
    ]
