services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn your_project_name.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
      - key: SECRET_KEY
        value: your_django_secret_key
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString
